### ISSUE TITLE
你好，配置文件我写成这样可以么

### ISSUE THREAD

**Issue by YangHgRi** [mohuishou/siyuan-sync-github#1]
不打算用图库，主要是想同步文本部分，另外我怎么触发同步，没看到按钮，谢谢

`var SiyuanSyncConfig = {
    baseURL: "https://github.com/YangHgRi/SiYuanDocs",

    // github 仓库配置
    github: {
        owner: "YangHgRi",
        repo: "SiYuanDocs",
        secret: "github_pat_xxx",
    },

    // 图床配置，支持所有兼容 s3 协议的对象存储
    // 例如 oss, cos, 七牛云 等
    s3: {
        accessKey: "",
        secretKey: "",
        endpoint: "https://oss-cn-hangzhou.aliyuncs.com",
        bucket: "",
        region: "oss-cn-hangzhou",
        prefix: "siyuan",
        // 自定义域名
        baseURL: "https://you-domain.com/"
    },
    sync: {
        // 文件保存文件夹
        dir: "source/_posts/siyuan/",
        // 文件名映射规则，以什么字段作为文件名，文件扩展名固定为 .md
        filename: {key: "urlname"},
        // 属性映射, yaml front matter 只会映射这配置了的属性
        attrs: {
            index_img: { key: "title-img" },
            categories: { key: "categories", type: "array" },
            tags: { key: "tags" },
            show_category: { default: true },
            date: { key: "updated_at" },
            urlname: { key: "urlname" },
            title: { key: "title" }
        },
        migratePictures: true
    }
}`

**Comment by mohuishou** [comment]
1. baseURL 不要修改，这个是思源的 api 地址
2. 如果不需要迁移图片，这个改为 false `migratePictures: false`

**Comment by mohuishou** [comment]
你没看到数据应该主要是改了 baseURL 的原因，配置修改后记得手动关闭挂件块所在的文档，然后重新打开

**Comment by YangHgRi** [comment]
写成这样了，但是挂架还是显示No Data
`var SiyuanSyncConfig = {
    baseURL: "http://127.0.0.1:6806",

    // github 仓库配置
    github: {
        owner: "YangHgRi",
        repo: "SiYuanDocs",
        secret: "github_pat_xxx",
    },

    // 图床配置，支持所有兼容 s3 协议的对象存储
    // 例如 oss, cos, 七牛云 等
    s3: {
        accessKey: "",
        secretKey: "",
        endpoint: "https://oss-cn-hangzhou.aliyuncs.com",
        bucket: "",
        region: "oss-cn-hangzhou",
        prefix: "siyuan",
        // 自定义域名
        baseURL: "https://you-domain.com/"
    },
    sync: {
        // 文件保存文件夹
        dir: "source/_posts/siyuan/",
        // 文件名映射规则，以什么字段作为文件名，文件扩展名固定为 .md
        filename: {key: "urlname"},
        // 属性映射, yaml front matter 只会映射这配置了的属性
        attrs: {
            index_img: { key: "title-img" },
            categories: { key: "categories", type: "array" },
            tags: { key: "tags" },
            show_category: { default: true },
            date: { key: "updated_at" },
            urlname: { key: "urlname" },
            title: { key: "title" }
        },
        migratePictures: false
    }
}`

**Comment by YangHgRi** [comment]
写成这样了，但是挂架还是显示No Data
`var SiyuanSyncConfig = {
    baseURL: "http://127.0.0.1:6806",

    // github 仓库配置
    github: {
        owner: "YangHgRi",
        repo: "SiYuanDocs",
        secret: "github_pat_xxx",
    },

    // 图床配置，支持所有兼容 s3 协议的对象存储
    // 例如 oss, cos, 七牛云 等
    s3: {
        accessKey: "",
        secretKey: "",
        endpoint: "https://oss-cn-hangzhou.aliyuncs.com",
        bucket: "",
        region: "oss-cn-hangzhou",
        prefix: "siyuan",
        // 自定义域名
        baseURL: "https://you-domain.com/"
    },
    sync: {
        // 文件保存文件夹
        dir: "source/_posts/siyuan/",
        // 文件名映射规则，以什么字段作为文件名，文件扩展名固定为 .md
        filename: {key: "urlname"},
        // 属性映射, yaml front matter 只会映射这配置了的属性
        attrs: {
            index_img: { key: "title-img" },
            categories: { key: "categories", type: "array" },
            tags: { key: "tags" },
            show_category: { default: true },
            date: { key: "updated_at" },
            urlname: { key: "urlname" },
            title: { key: "title" }
        },
        migratePictures: false
    }
}`

**Comment by YangHgRi** [comment]
网络伺服也打开了

**Comment by mohuishou** [comment]
你这个挂件块的的文档下有子文档么？

**Comment by YangHgRi** [comment]
没有，我新开了个笔记本，除了放一起还有办法配置么

**Comment by mohuishou** [comment]
目前只会获取挂件块所在文档下的子文档哈

**Comment by YangHgRi** [comment]
好滴，谢谢

**Comment by YangHgRi** [comment]
诶，我这边子文件夹下的md文件不能识别到，有办法解决么，文档量挺大的，拆出来在一级目录平摊很难受

**Comment by mohuishou** [comment]
> 诶，我这边子文件夹下的md文件不能识别到，有办法解决么，文档量挺大的，拆出来在一级目录平摊很难受

这个我后面改一下哈，目前暂时应该不行

**Comment by mohuishou** [comment]
> 诶，我这边子文件夹下的md文件不能识别到，有办法解决么，文档量挺大的，拆出来在一级目录平摊很难受

我试了一下，子目录现在就是可以的
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/15172509/202204157-9d264341-f330-4571-81b6-53b29cf4d748.png">
