### ISSUE TITLE
> 诶，我这边子文件夹下的md文件不能识别到，有办法解决么，文档量挺大的，拆出来在一级目录平摊很难受

### ISSUE THREAD

**Issue by YangHgRi** [mohuishou/siyuan-sync-github#2]
> 诶，我这边子文件夹下的md文件不能识别到，有办法解决么，文档量挺大的，拆出来在一级目录平摊很难受

这个我后面改一下哈，目前暂时应该不行

_Originally posted by @mohuishou in https://github.com/mohuishou/siyuan-sync-github/issues/1#issuecomment-1316682549_
      
好滴，谢谢

**Comment by mohuishou** [comment]
支持自定义 sql 查询了哈 https://github.com/mohuishou/siyuan-sync-github/releases/tag/v0.1.0

使用说明可以查看 readme 中的 FAQ

**Comment by YangHgRi** [comment]
> 支持自定义 sql 查询了哈 https://github.com/mohuishou/siyuan-sync-github/releases/tag/v0.1.0
> 
> 使用说明可以查看 readme 中的 FAQ

感谢，🐮的
