### ISSUE TITLE
修改文档后怎么重新发布

### ISSUE THREAD

**Issue by sumcai** [mohuishou/siyuan-sync-github#3]
首先感谢作者，这个插件还是挺实用的，正在尝试中。

有个问题，文档发布后， 如果修改了内容， 怎么再次发布更新， 如截图， 此时发布按钮是不能再点击的
![image](https://user-images.githubusercontent.com/76768485/206222111-dc8dc53b-f946-484d-93c0-713fcaba4917.png)

**Comment by mohuishou** [comment]
点下刷新就行了

**Comment by sumcai** [comment]
> 点下刷新就行了

果然是这样， 很细节，  感谢
