### ISSUE TITLE
updated_at 和 created_at好像获取反了

### ISSUE THREAD

**Issue by sumcai** [mohuishou/siyuan-sync-github#4]
这两个属性好像搞反了，显示的updated_at比created_at早
config中attr配置：
            updated_at: { key: "updated_at", column: { show:true, label:"更新时间"} },
            created_at: { key: "created_at", column:{ show:true, label:"创建时间"} },

**Comment by sumcai** [comment]
补充：测试了几次，update_at数据没问题， create_at获取的不是创建时间而是当前时间

**Comment by mohuishou** [comment]
这个没问题， created at 就是文档的创建时间

**Comment by sumcai** [comment]
> 这个没问题， created at 就是文档的创建时间

测试了， 获取的是当前时间， 不是文档创建时间

**Comment by sumcai** [comment]
> > 这个没问题， created at 就是文档的创建时间
> 
> 测试了， 获取的是当前时间， 不是文档创建时间

已提交pr，属性都是从 blocks.ial 中解析的，ial只有内部属性， 常用属性都在blocks中，包括created
